services:
  # Service buat Python Engine (Lo, Ca!)
  engine:
    build:
      context: ./ezsign-engine
      dockerfile: Dockerfile
    container_name: ezsign_analytics_engine
    volumes:
      - ./ezsign-engine:/app
      - ./data:/data # Shared Volume
    environment:
      - STAGING_PATH=/data/staging
      - PYTHONUNBUFFERED=1
      - DATABASE_PATH=/data/database.sqlite
      - CORPORATE_CODE=ezsign
      - CORPORATE_NAME=PT Solusi Identitas Global Net
    restart: always